variables:
  - group: td.deploy

jobs:
  - job: BuildModule

    pool:
      vmImage: "windows-2022"

    steps:
      - task: NuGetToolInstaller@1
        inputs:
          checkLatest: true

      - task: NuGetAuthenticate@1

      - task: AzurePowerShell@5
        displayName: "Build and Test"
        condition: and(succeeded(), ne(variables['BuildType'], 'release') )
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          CodeSigningAccountName: $(CodeSigningAccountName)
          CertificateProfileName: $(CertificateProfileName)
          SigningEndpoint: $(SigningEndpoint)
        inputs:
          azureSubscription: "vs-sub"
          scriptType: filePath
          scriptPath: "./build.ps1"
          scriptArguments: ""
          azurePowerShellVersion: latestVersion
          pwsh: true

      - task: AzurePowerShell@5
        displayName: "Build, Test and Publish"
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.Reason'], 'Schedule'), eq(variables['BuildType'], 'release') )
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          CodeSigningAccountName: $(CodeSigningAccountName)
          CertificateProfileName: $(CertificateProfileName)
          SigningEndpoint: $(SigningEndpoint)
        inputs:
          azureSubscription: "vs-sub"
          scriptType: filePath
          scriptPath: "./build.ps1"
          scriptArguments: "-Publish $true"
          azurePowerShellVersion: latestVersion
          pwsh: true

      - task: PublishTestResults@2
        inputs:
          testRunner: "NUnit"
          testResultsFiles: "**/Test-*.xml"
          testRunTitle: "Unit Tests"
          failTaskOnFailedTests: true
        displayName: "Publish Test Results **/Test-*.xml"
        condition: succeededOrFailed()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifacts"
        inputs:
          PathtoPublish: output
          ArtifactName: drop
          publishLocation: Container
          Parallel: true
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.Reason'], 'Schedule'), eq(variables['BuildType'], 'release') )
